formats:
 jsonld: [‘application/ld+json'] # first one is the default format
 json: ['application/json']
 jsonhal: ['application/hal+json']
 xml: ['application/xml', 'text/xml']
 yaml: ['application/x-yaml']
 csv: ['text/csv']
 html: ['text/html']